language: go
go:
  - master 
install:
  - go get github.com/gohugoio/hugo
script:
  - hugo
deploy:
  provider: pages
  repo: ReverentEngineer/ReverentEngineer.github.io
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  keep-history: true
  on:
    branch: master
